export const bestSellers = [
  {
    id: 1,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 2,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 3,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 4,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 5,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 6,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 7,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 8,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 9,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 10,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 11,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
  {
    id: 13,
    name: "Stick Pailleté Multi-Usage Icy Sparkly",
    image: "/assets/yeux.png",
    price: 12.9,
    description: "Brillant longue tenue",
  },
];
